### ISSUE TITLE
Site's Main Image

### ISSUE THREAD

**Issue by TonyRolfe** [nelson-david/react-homestead#2]
The site's main picture needs to be updated to correspond more with the dating theme of the site. Here's a public use picture that we can use on the site that looks really appropriate:

![PIXNIO-2464962-5760x3840](https://user-images.githubusercontent.com/35072659/128442045-9b2a2440-ea77-4f03-8ecb-bb2b09f336b5.jpeg)

**Comment by nelson-david** [comment]
Fixed this issue
